version: '3.7'
services:
  postgres:
    image: postgres:14.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    logging:
      options:
        max-size: 10m
        max-file: "3"
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./pf-foundry/postgres/sql/create_tables.sql:/docker-entrypoint-initdb.d/05-create_tables.sql
      - ./pf-foundry/postgres/sql/insert_test_data.sql:/docker-entrypoint-initdb.d/10-insert_test_data.sql
      # # copy the sql script to fill tables
      # - ./postgres/sql/fill_tables.sql:/docker-entrypoint-initdb.d/02-fill_tables.sql

  foundry:
    build:
      context: pf-foundry
      dockerfile: ./Dockerfile
    depends_on:
      - postgres
    ports:
      - 8080:8080

  web:
    build:
      context: pf-web
      dockerfile: ./Dockerfile
    depends_on:
      - foundry
    ports:
      - 8280:8280
      - 8290:8290
      - 9630:9630

volumes:
  postgres-data:
